### ISSUE TITLE
ubuntu 20.04 LTS: sys/types.h: No such file or directory

### ISSUE THREAD

**Issue by Karol-G** [evg-zhabotinsky/libspeedhack#1]
Hi,

I wanted to test your speedhack lib with a small flash game on my Ubuntu 20.04 LTS.
However when I run `make` I get the error `sys/types.h: No such file or directory`.
Any idea how to solve this?

Best,
Karol

**Comment by evg-zhabotinsky** [comment]
On my system it is provided by `libc6-dev`.

Not sure it'll work for flash player, though. What I've found by trying my implementation on various games is that there are **tons** of ways to get time, and you have to catch all that a specific game or app uses. If you catch some but not all, things might e.g. work for a while and then crash or hang, and overall behave weirdly.

The proper solution would be butcher `strace` to, instead of logging all syscalls, only override the values returned by the time-related ones.

**Comment by Karol-G** [comment]
Hi again,

I managed to get it working. I had to use Ubuntu 18. I will probably try to get it running on Ubuntu 20 in the future though. On Ubuntu 18 I just had to install `libc6-dev`. 
It seems to work with the flash game which is great!
Values in the range [0,5] work without problems and the slowdown/speedup seems correct.
However if I set the speedup to something like 50 for example it is still only as fast as if it is 5.
Do you know if this is a limitation of your program or of my CPU/GPU?

Best,
Karol

**Comment by Bloodiko** [comment]
The issue is probably - that you only used "make" as command.
This defaults to make 32bit - means: it does look for the i386 base lib versions 
Those are most likely not installed if you are running a 64Bit System.

just use `make 64bit` (whe you are on a lib 64 system)
or install `sudo apt install libc6-dev:i386` before you run `make`

**Comment by evg-zhabotinsky** [comment]
Done some fixing and updated README.
The package missing was `g++-multilib`, as is now stated in README, it is required to build the 32-bit version.
Now by default only the "native" version is built, so use `make multilib` if you care about 32-bit games.
