### ISSUE TITLE
SteamOS sys/types.h error (+flatpak question) 

### ISSUE THREAD

**Issue by stefanow30** [evg-zhabotinsky/libspeedhack#12]
Hi,
I'm having trouble trying to build libspeedhack on SteamOS (Arch based); it's difficult for a newbie to install anything more than flatpak, since it has immutable filesystem. Btw: I don't know if it is possible, but please consider making flatpak, since growing number of Steam Deck users would gladly use so usefool tool, but lacks knowledge of linux building process.

I managed to turn off this feature, update keyrings, install missing dependencies, but make command (make 64bit changes nothing) gives me error:

==> Starting package()...
mkdir -p lib
g++ -std=c++11 -Wall   -fPIC -shared libspeedhack.cpp -ldl -o lib/libspeedhack.so
libspeedhack.cpp:1:10: fatal error: sys/types.h: No such file or directory
    1 | #include <sys/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:20: lib/libspeedhack.so] Error 1
==> ERROR: A failure occurred in package().
    Aborting...

I've read that libc6-dev/g++-multilib could be needed, but it's not available on Arch; maybe it has Arch equivalent, but I'm new to this, so please, be indulgent ;)

**Comment by evg-zhabotinsky** [comment]
Huh, SteamOS moved ftom Debian to Arch? Interesting.

Anyway, I don't think it is possible to package a tool like this as a flatpak, by design. From a cursory glance around the web, you can run a flatpak unsandboxed, but that is highly nontrivial and defeats the whole purpose of flatpaks, which is bundling **everything** an app uses with it and running it isolated from everything else to ensure predictability.

Also note, that if the games themselves are flatpak-ed, you would have to work around that somehow, because flatpak by default would sandbox and thus "protect" them from libspeedhack that is outside that flatpak. (By the way, a workaround for the same behavior of Steam's "Pressure Vessel" runtime, that's mandatory e.g. for Proton and thus Windows games, can be found here: https://github.com/evg-zhabotinsky/libspeedhack/issues/8#issuecomment-1000433033 .)

As for the build issues, luckily the library is simple enough that it doesn't have many dependencies. I finally published a release, which judging by the README I was planning from the start, but judging by the last 3 hours previously gave up on because making the compiler do what I want is a huge pain in the @$$. Anyway, you can find that release on the "Releases" page of this repo: https://github.com/evg-zhabotinsky/libspeedhack/releases Should be a "good enough" alternative to a flatpak, because you don't really need to install it anyway.

**Comment by evg-zhabotinsky** [comment]
Oh, and by the way: Right now I'm on Arch myself (Manjaro, more specifically), and libspeedhack builds just fine for me, including multilib, but I honestly have no clue which packages provide all the tools and libs that are needed for that ¯\\\_(ツ)\_/¯ I've just been installing stuff for quite a while, and nowadays it just works most of the time.

**Comment by stefanow30** [comment]
Thanks for the release; running glxgears proves it's working. Trying it in game however (Pinball FX3 on Steam) gives no similar effect, even with mentioned 'pressure-vent.sh'. I guess it's like Loop Odyssey case then.
