### ISSUE TITLE
using libspeedhack with already running process

### ISSUE THREAD

**Issue by ibrahemesam** [evg-zhabotinsky/libspeedhack#5]
I wanna slow down a running process. not running it from the start
(ie: give  libspeedhack the pid of that running process as an argument)
--------------------------------------
I use Python PyQt5 QWebEngineView to view an online flash game.
the problem is that the QWebEngineProcess that runs flash PPAPI consumes about 40% of the CPU.
that process is automatically created by the C++ code (not from Python)
, so I need to use  libspeedhack with that already running process.
I wanna slow it down to lower its usage by half.
I know that I can use [cpulimit] on Linux, but I also sometimes need to speed up the process  for hack purposes.

**Comment by evg-zhabotinsky** [comment]
First, `libspeedhack` doesn't "slow down" the process, it only changes its "perception of time", so CPU usage might not be affected at all, or might even increase in some weird cases. Not the right tool, `cpulimit` is probably better. Analogy: slowing down all clocks on a spaceship won't help with oxygen consumption by crew. (Though, actually, limiting oxygen supply isn't perfect either, crew might start lagging. xD )

Now to the second part, attaching to a running process.

First, do you really need to? Is running the whole thing under libspeedhack unacceptable?

I'm afraid it isn't possible to just attach to an existing process. The first library to load (i.e. from LD_PRELOAD) that contains a function provides its "default" implementation, and that is pretty much impossible to override later. But that overriding is exactly what libspeedhack needs.

One possibility is, after everything is loaded, to find whatever implementation ended up being default, and patch its code after the fact, which can be done through an attached debugger. But it also is a royal pain, because you need that implementation untouched too as `libspeedhack` provides just wrappers, not reimplementations.

Another option is to load the overriding library (libspeedhack) right away, but not "activate" it unless we are in the right process. Checking `argv[]` might be the easiest option here, if it works. And checking `/proc/self/cmdline` might be the easiest way to do that.

And the final option is to use `ptrace` (the thing debuggers use) directly to catch time-related syscalls and to remap `vdso` page for virtual syscalls and adjust time there. That would allow for both attaching to running processes and catching every single attempt by app to get time (while current approach misses some).

In any case, that would be almost entirely another project, so here it is is a "wontfix".
