### ISSUE TITLE
Permission denied & .exe not found

### ISSUE THREAD

**Issue by alexholox** [evg-zhabotinsky/libspeedhack#7]
https://github.com/evg-zhabotinsky/libspeedhack/issues/1 I saw this issue and didn't help my problem, I'm on **openSUSE Tumbleweed** and this isn't anywhere near the repos.

Basically, I follow instructions, put the .exe path and I always have 2 errors: destination not found or permission denied. I use it for non-native Windows games bought from GOG, and this speedhack will never run. I installed native, normal and multilib, and none of this three options solved anything but I'm currently on multilib, where only 64 bit files are created, my file is that. there is an error when nstalling multilib saying 32 bit files couldn't be created.

The issue is not being able to use this as it will end in error. Please help. Many thanks for your time.

**Comment by evg-zhabotinsky** [comment]
I assume by saying "put the .exe path" you imply "after wine command", normally .exe won't run without explicitly calling Wine. (GUI file managers "open" .exe like, say, a .jpg, they don't "run" it per se.)

On the point of 32 bits, you probably need them, because most older games are 32-bit. On Suse the required tools seem to come in the gcc-32bit package, install it and `make multilib` should work. If something is still missing I'd look for other *-32bit packages.

And finally, you might want to try Windows-specific speedhack solutions, of which there are at least several. I'm not sure if Wine implements all required APIs, but I'm sure that current libspeedhack implementation has little to no effect on the few Windows games I tried it on.

**Comment by evg-zhabotinsky** [comment]
No response received, closing. Please reopen if you have something to add.
